### ISSUE TITLE
Unit tests fail on Linux

### ISSUE THREAD

**Issue by nojaf** [markashleybell/MAB.DotIgnore#15]
Hello, when using this NuGet package I developed on Windows and everything seemed fine on my machine.
But when I run my CI pipeline I noticed that my build is failing on Linux.

Then I tried to run the unit tests inside a Docker container and I noticed that 14 tests fails.

Steps to reproduce:
> docker run -it --rm -w "/usr/src/app" mcr.microsoft.com/dotnet/core/sdk:2.1
> git clone https://github.com/markashleybell/MAB.DotIgnore
> cd MAB.DotIgnore
> dotnet build
> cd MAB.DotIgnore.Test/
> dotnet test

Is this project meant to be cross-platform?

**Comment by markashleybell** [comment]
Hi! To be honest, it's been a couple of years since I released the last version of this library, and at that point, platforms other than Windows weren't really a consideration.

However, I definitely feel it should be cross-platform _now_, so I'm keen to get it working!

Give me a bit of time to get this up and running again and I'll check it out.

**Comment by markashleybell** [comment]
On first look, there are a bunch of hard-coded backslashes in file paths in the test project, which I suspect is probably the cause of a few of the problems...

**Comment by markashleybell** [comment]
@nojaf I can't even get the project to _build_ on Linux, which would make sense, because the library targets `net40`, which just isn't available on Linux systems. I'm curious how you managed to get to the point where you could see the test output?

![image](https://user-images.githubusercontent.com/483470/91835788-c4fa7880-ec41-11ea-91dc-e56096c4dafa.png)

Were you running a Windows docker container, perhaps? Or is there something else I'm missing?

**Comment by nojaf** [comment]
I think I removed, the `net40` part to test in this in Linux.

**Comment by markashleybell** [comment]
Ok, you should find this works fine now. The file paths in the tests were the main cause of the test failures (see d6d0dcb), but I also learned today that there are now [reference assembly packages](https://github.com/Microsoft/dotnet/tree/master/releases/reference-assemblies) available to enable exactly this kind of build scenario for non-Windows OSes. 

This will help me when setting up a CI pipeline for this library too, so thanks for the heads-up!

**Comment by nojaf** [comment]
Tried it with the latest master, two tests are still failing for me:
```
root@3661c0fe2d32:/usr/src/app/MAB.DotIgnore.Test# dotnet test
Test run for /usr/src/app/MAB.DotIgnore.Test/bin/Debug/netcoreapp3.1/MAB.DotIgnore.Test.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  X File_Rule_Line_Numbers_ToString [55ms]
  Error Message:
     Expected: True
  But was:  False

  Stack Trace:
     at MAB.DotIgnore.Tests.IgnoreLogTests.File_Rule_Line_Numbers_ToString() in /usr/src/app/MAB.DotIgnore.Test/IgnoreLogTests.cs:line 97

  X Log_ToString [6ms]
  Error Message:
     Expected: True
  But was:  False

  Stack Trace:
     at MAB.DotIgnore.Tests.IgnoreLogTests.Log_ToString() in /usr/src/app/MAB.DotIgnore.Test/IgnoreLogTests.cs:line 76


Test Run Failed.
Total tests: 72
     Passed: 70
     Failed: 2
 Total time: 3.9061 Seconds
/usr/share/dotnet/sdk/3.1.401/Microsoft.TestPlatform.targets(32,5): error MSB4181: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task returned false but did not log an error. [/usr/src/app/MAB.DotIgnore.Test/MAB.DotIgnore.Test.csproj]
```

**Comment by markashleybell** [comment]
Hmm... OK, thanks!

The thing those two tests have in common (as opposed to all the others) is that they both compare against a string which contains newlines. Something to do with Windows/Unix newline mismatch, perhaps? Git `autocrlf` setting? 

The question is, why _don't_ they fail for me, when I'm running in a Linux Docker image? I'm a bit stumped on that one, for the minute...

**Comment by nojaf** [comment]
Ah good thinking, yes I checked the code out in Windows, mounted a volume in Linux so that adds up.
