### ISSUE TITLE
Strong signing

### ISSUE THREAD

**Issue by flcdrg** [markashleybell/MAB.DotIgnore#6]
Hey, great project. However I went to use it as part of a free Visual Studio Extension I've written and VS freaks out because the assembly isn't signed.

**Comment by markashleybell** [comment]
Hi, thanks for the feedback.

I'm afraid that for now I'm going to leave the assembly unsigned, until I understand more about the [implications of signing](http://blog.marcgravell.com/2014/06/snk-we-need-to-talk.html) and can figure out a way to do it while still protecting the private key. 

As a workaround however, the following package (disclaimer: I haven't tried it yet) gives you tooling which will let you automate the signing of the assembly yourself, in order to get your extension up and running:

https://www.nuget.org/packages/strongnamer

Hope this helps—good luck with the project!

**Comment by flcdrg** [comment]
I've read that article before, but I must be missing something because I'm still not clear what the big issue is with signing public libraries - other than possibly some principled stand against having to sign things. It just means that it works for pretty much every scenario, rather than just for a subset. Many public libraries just check in the .snk file anyway (eg. [AutoMapper](https://github.com/AutoMapper/AutoMapper/tree/master/src)).

For now, I've forked the project, signed it and just copied the assembly locally. If you do end up signing in the future, then i'll be glad to throw my fork away :-)

**Comment by markashleybell** [comment]
Nothing particular against signing here—it's simply that I don't _understand_ enough about the process to “just do it.” 

Right off the bat it seems wrong to me to have to include a private key in a completely public source code repository... but as I said, having no experience with signing assemblies (apart from a few times _many_ years ago, when we were still using the GAC), I'm still unsure what the correct way to approach it is.

Keep an eye on this issue, there may well be an update as soon as I've had time to research this more.

**Comment by markashleybell** [comment]
You'll be glad to hear that I have finally got around to doing this!

I was initially very wary, as this is referenced by a couple of heavily used applications where I work, and I've been bitten by strong-naming issues before. 

However, the [official advice now steers us toward signing public NuGet libraries](https://docs.microsoft.com/en-gb/dotnet/standard/library-guidance/strong-naming), and as I now properly understand the process, I've decided to take the plunge.

There is an RC here: https://www.nuget.org/packages/MAB.DotIgnore/2.0.0-rc

I am testing with my apps and all seems fine. 

When you get a minute, would you mind upgrading your project to use that version and confirming that it works OK please? If so I'll push the 2.0.0 release ASAP.

**Comment by atifaziz** [comment]
This is now closed by 50106c96e5b88af3b760143d0b8bd86a68208244, right?

**Comment by markashleybell** [comment]
That's correct, but I'm just doing a bit more testing before I push the update to NuGet. I was also hoping @flcdrg could test his code with it before I pushed the final release, but I assume he's busy!

Anyway, I'll update this when 2.0.0 is live.

**Comment by flcdrg** [comment]
yeah, sorry. I haven't had a chance to try it out, but I'm sure it's fine.

**Comment by markashleybell** [comment]
@flcdrg Not a problem at all, it took me two years to make the change, so I certainly don't expect you to drop everything now!

**Comment by markashleybell** [comment]
As of [2.0.0](https://www.nuget.org/packages/MAB.DotIgnore/2.0.0), the library now has a strong name.
